# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/centos-7.4"

  # rpmをキャッシュしてyum installを高速化するプラグイン
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provider :virtualbox do |vb|
    vb.name = "e-go"
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.synced_folder "../", "/home/vagrant/e-go",
    create: true, owner: "vagrant", group: "vagrant"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.limit = "all"
  end
end
